# az ml compute create -f infra/compute-cluster.yml --workspace mlw-mlops
$schema: https://azuremlschemas.azureedge.net/latest/amlCompute.schema.json
name: mlw-mlops-cluster
type: amlcompute
size: STANDARD_DS11_V2
min_instances: 0
max_instances: 2
idle_time_before_scale_down: 120
identity:
  type: system_assigned
