# az ml job create -f infra/job.yml --workspace "mlw-mlops"
$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ../src/model
command: >-
  python 
  train.py
  --training_data
  ${{ inputs.training_data }}
inputs:
  training_data: 
    type: uri_folder 
    path: azureml:diabetes-prod-folder@latest
  reg_rate: 0.01
environment: azureml:AzureML-sklearn-1.1-ubuntu20.04-py38-cpu@latest
compute: azureml:mlw-mlops-cluster
identity:
  type: managed
