name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  manual-trigger:
    uses: ./.github/workflows/train-job.yml
    with:
      dataset: experimentation
      environment: development
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
