name: Code checks

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install -r requirements.txt
    - name: Run linting on src
      run: | 
        flake8 src/model/
    - name: Run linting on tests
      run: | 
        flake8 tests/
  job2:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install -r requirements.txt
    - name: Run tests
      run: | 
        pytest tests/
