name: Run experiments

on:
  pull_request:
    branches:
      - main

jobs:
  experimentation:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: run job
      run: az ml job create -f infra/job.yml --resource-group "rg-internal" --workspace "mlw-mlops" --stream
  production:
    runs-on: ubuntu-latest
    environment: production
    needs: experimentation
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: run job
        run: az ml job create -f infra/job.yml --resource-group "rg-internal" --workspace "mlw-mlops" --stream