name: Run experiment

on:
  workflow_call:
    inputs:
      run_id:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Register model
      run: az ml model create --name diabetes-model --path runs:/${{inputs.run_id}}/model/ --type mlflow_model --resource-group "rg-internal" --workspace "mlw-mlops"
    - name: Create endpoint
      run: az ml online-endpoint update --file infra/endpoint.yml --resource-group "rg-internal" --workspace "mlw-mlops"
    - name: Deploy model
      run: az ml online-deployment update --file infra/deployment.yml --resource-group "rg-internal" --workspace "mlw-mlops"
