name: Run experiments

on:
  pull_request:
    branches:
      - main

jobs:
  experimentation:
    uses: ./.github/workflows/train-job.yml
    with:
      dataset: experimentation
      environment: development
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
  production:
    uses: ./.github/workflows/train-job.yml
    needs: experimentation
    with:
      dataset: production
      environment: production
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
  deploy-model:
    uses: ./.github/workflows/deploy-model.yml
    needs: production
    with:
      run_id: ${{needs.experimentation.outputs.run_id}}
      environment: production
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
