name: Run experiments

on:
  pull_request:
    branches:
      - main

jobs:
  experimentation:
    uses: ./.github/workflows/train-job.yml
    with:
      dataset: experimentation
      environment: development
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
  production:
    uses: ./.github/workflows/train-job.yml
    needs: experimentation
    with:
      dataset: production
      environment: production
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
  register-model:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: echo
        uses: ${{outputs
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Run job
        run: az ml job create -f infra/job-${{inputs.dataset}}.yml --resource-group "rg-internal" --workspace "mlw-mlops" --stream

