name: Run experiments

on:
  pull_request:
    branches:
      - main

jobs:
  experimentation:
    uses: ./.github/workflows/train-job.yml
    with:
      dataset: experimentation
      environment: development
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
  register-model:
    runs-on: ubuntu-latest
    needs: experimentation
    steps:
      - run: az ml model create --name model --path runs:/${{needs.experimentation.outputs.run_id}}/model/ --type mlflow_model --resource-group "rg-internal" --workspace "mlw-mlops"
  production:
    uses: ./.github/workflows/train-job.yml
    needs: experimentation
    with:
      dataset: production
      environment: production
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
#  register-model:
#    runs-on: ubuntu-latest
#    environment: production
#    needs: experimentation
#    steps:
#      - name: echo
#        uses: ${{needs.production.outputs.step}}
