name: Run experiments

on:
  pull_request:
    branches:
      - main

jobs:
  experimentation:
    uses: ./.github/workflows/train-job.yml
    with:
      dataset: diabetes-dev-folder
      environment: development
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
  production:
    uses: ./.github/workflows/train-job.yml
    with:
      dataset: diabetes-prod-folder
      environment: production
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
