name: Run experiment

on:
  workflow_call:
    inputs:
      dataset:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  train:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run job
      run: az ml job create -f infra/job-${{inputs.dataset}}.yml --resource-group "rg-internal" --workspace "mlw-mlops" --stream
