name: Run experiment

on:
  workflow_call:
    inputs:
      dataset:
        required: true
        type: string
      environment:
        required: true
        type: string
    outputs:
      run_id:
        value: ${{jobs.train.outputs.run_idg}}
    secrets:
      AZURE_CREDENTIALS:
        required: true
jobs:
  train:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    outputs:
      run_id: ${{ steps.run.outputs.run_id }}
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Run job
      id: run
      run: |
        res=$(az ml job create -f infra/job-${{inputs.dataset}}.yml --resource-group "rg-internal" --workspace "mlw-mlops" --query name -o tsv)
        echo $res
        echo "run_id=$res" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - env:
          OUTPUT1: ${{needs.train.outputs.run_id}}
        run: echo "da $OUTPUT1"